### PR TITLE
Generates QR code in terminal for public link

### PR DESCRIPTION
**Pull request by theevilhead**
Generates a QR code inside terminal for public links so that it will be easier to view on mobile & share

### CODE REVIEW

**Comment by Floriferous** [comment]
I was looking for this feature, would be a great addition, especially for free users when you have to type in the random URL into a mobile device.

**Comment by mislam** [comment]
This will be a very useful feature. Instead of typing the long url on mobile, just take a snap with the camera and boom.

**Comment by rsmelo92** [comment]
Very useful, was going to implement it, thank you

**Comment by noneissome** [comment]
This is very helpful, but @inconshreveable won't be updating this anymore with new features like this. Maybe just fork it and put it there? @theevilhead

**Comment by noneissome** [comment]
> @noneissome Yep you can find it here https://github.com/theevilhead/ngrok

Shall check it out, thanks 😃

**Comment by skratchdot** [comment]
I was looking for similar functionality.  I'm assuming the ngrok code has moved to a private repository?

Anyways, I found this b/c I was going to submit a PR for the "web interface" to show qr codes on the "status page".  I couldn't find the source code for the current web interface, but I did find this pr.  I decided to create a bookmarklet instead of submitting a PR (since I couldn't find the source).

For anyone interested, here is the bookmarklet:
```
javascript:(() => {const s = document.createElement('script');s.src = 'https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js';s.onload = () => {[...document.querySelectorAll('th')].filter(el => el.innerHTML === 'URL').forEach(el => {const td = el.parentElement.children[1];const url = td.innerHTML;const div = document.createElement('div');el.appendChild(div);new QRCode(div, url);});};document.body.appendChild(s);})();
```

https://gist.github.com/skratchdot/c99a52b9228faf72999ef1bea293fe15

**Comment by hamala69** [comment]
> code

pls i need to setup this

**Comment by developius** [comment]
Here's an updated version of @skratchdot's bookmarklet for newer versions of ngrok (tested against 3.3.1):

```
javascript:(() => {const s = document.createElement("script"); s.src = "https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"; s.onload = () => {[...document.querySelectorAll(".tunnels")].forEach(el => {const url = el.textContent; const div = document.createElement("div"); el.appendChild(div); new QRCode(div, url); }); }; document.body.appendChild(s);})();
```

**Comment by russorat** [comment]
Thank you for your contribution! This repository is no longer actively maintained. For the latest version of ngrok, please visit [https://ngrok.com](https://ngrok.com).

**Pull request closed without merging**
